### ISSUE TITLE
Core Migrations create invalid YAML changes

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#1351]
There are at least two core migrations that break the `NodeTypes` configuration when using the (recommended) `superTypes` "flag"-syntax.

Background:
Previously the node super- and child node types were expected to be defined as simple array.
`TYPO3.TYPO3CR-130523180140` and `TYPO3.TYPO3CR-20150510103823` both expect this and apply `str_replace()` to the array item:

```php
foreach ($configuration as &$nodeType) {
    if (isset($nodeType['superTypes'])) {
        foreach ($nodeType['superTypes'] as &$superType) {
            $superType = str_replace('TYPO3.Neos:Page', 'TYPO3.Neos.NodeTypes:Page', $superType);
        }
    }
   // ...
```

The result is that a configuration of:

```yaml
'Some:NodeType':
  superTypes:
    'TYPO3.Neos:Content': true
```

is replaced with

```yaml
'Some:NodeType':
  superTypes:
    'TYPO3.Neos:Content': '1'
```

A simple

```php
if (is_bool($superType)) {
    continue;
}
```

fixes the issue but if we want to support both syntaxes it gets a bit more complex.

**Comment by aertmann** [comment]
this is a really old issue and AFAIR was fixed with a later migration

**Comment by johannessteu** [comment]
If you run all migrations it will end up something like this:
![screen shot 2016-12-20 at 17 25 57](https://cloud.githubusercontent.com/assets/769789/21382086/1e5738ac-c75f-11e6-8340-967f86645396.png)

Then another migration will transform it to something like this:

![screen shot 2016-12-20 at 17 29 10](https://cloud.githubusercontent.com/assets/769789/21382088/240243f0-c75f-11e6-8d71-30553babf140.png)

And the next migration that adjusts the yaml file will remove the `'': true`

So guess this is a blocker for 3.0

**Comment by bwaidelich** [comment]
> this is a really old issue and AFAIR was fixed with a later migration

Right, `TYPO3.TYPO3CR-20150510103823` seems to (partly!) revert the modifications, but it must not be fixed with a later migration but by fixing the affected migrations IMO.

I'll take care

**Comment by bwaidelich** [comment]
FYI: I changed the title and removed the "Next major" label as this should indeed be fixed with a separate migration (adjusted with 5223241a).
I'm still convinced that we should keep existing core migrations in sync with changed behavior/syntax in order not to create needles or invalid commits

**Comment by kdambekalns** [comment]
The reason for another migration fixing this was (IIRC) that the migration breaking things was released and used already. So we couldn't (only) fix it, since people already had broken results.

**Comment by bwaidelich** [comment]
> The reason for another migration fixing this was (IIRC) that the migration breaking things was released and used already

Yes, that makes sense. Still for anyone upgrading now (and applying core migrations to a new package) it means two needless commits (that might corrupt the config and/or delete comments). So tweaking existing migrations *on top* of the fixing migrations is the way to go in my opinion

**Comment by ComiR** [comment]
I still get the problem on running all migrations at once, so noting "fixed" here 👎

**Comment by albe** [comment]
not both? I mean a setting of string `0` should still be migrated to a `false`, right?

**Comment by ComiR** [comment]
should be, but won't be set to `'0'` by other migrations ;)

**Comment by bwaidelich** [comment]
Fixed with #1530
